package modelo.hibernate;
// Generated 23-oct-2017 11:55:10 by Hibernate Tools 5.2.5.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Articulo generated by hbm2java
 */
@Entity
@Table(name="articulo")
public class Articulo implements java.io.Serializable {
	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	@Column(name="codigo_articulo")
	private Integer codigoArticulo;
	@Column(name="nombre")
	private String nombre;
	@Column(name="codigo_genero")
	private int codigoGenero;
	@Column(name="plataforma")
	private String plataforma;
	@Column(name="fecha_de_lanzamiento")
	private Date fechaDeLanzamiento;
	@Column(name="informacion_adicional")
	private String informacionAdicional;
	@Column(name="stock")
	private int stock;
	@Column(name="clave")
	private int clave;

	public Articulo() {
		
	}

	public Articulo(String nombre, int codigoGenero, String plataforma, Date fechaDeLanzamiento, int stock,
			int clave) {
		this.nombre = nombre;
		this.codigoGenero = codigoGenero;
		this.plataforma = plataforma;
		this.fechaDeLanzamiento = fechaDeLanzamiento;
		this.stock = stock;
		this.clave = clave;
	}

	public Articulo(String nombre, int codigoGenero, String plataforma, Date fechaDeLanzamiento,
			String informacionAdicional, int stock, int clave) {
		this.nombre = nombre;
		this.codigoGenero = codigoGenero;
		this.plataforma = plataforma;
		this.fechaDeLanzamiento = fechaDeLanzamiento;
		this.informacionAdicional = informacionAdicional;
		this.stock = stock;
		this.clave = clave;
	}

	public Integer getCodigoArticulo() {
		return this.codigoArticulo;
	}

	public void setCodigoArticulo(Integer codigoArticulo) {
		this.codigoArticulo = codigoArticulo;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public int getCodigoGenero() {
		return this.codigoGenero;
	}

	public void setCodigoGenero(int codigoGenero) {
		this.codigoGenero = codigoGenero;
	}

	public String getPlataforma() {
		return this.plataforma;
	}

	public void setPlataforma(String plataforma) {
		this.plataforma = plataforma;
	}

	public Date getFechaDeLanzamiento() {
		return this.fechaDeLanzamiento;
	}

	public void setFechaDeLanzamiento(Date fechaDeLanzamiento) {
		this.fechaDeLanzamiento = fechaDeLanzamiento;
	}

	public String getInformacionAdicional() {
		return this.informacionAdicional;
	}

	public void setInformacionAdicional(String informacionAdicional) {
		this.informacionAdicional = informacionAdicional;
	}

	


	public int getClave() {
		return this.clave;
	}

	public void setClave(int clave) {
		this.clave = clave;
	}

	/**
	 * @return the stock
	 */
	public int getStock() {
		return stock;
	}

	/**
	 * @param stock the stock to set
	 */
	public void setStock(int stock) {
		this.stock = stock;
	}

}
