package modelo.hibernate;
// Generated 23-oct-2017 11:55:10 by Hibernate Tools 5.2.5.Final

import java.util.Date;

/**
 * Articulo generated by hbm2java
 */
public class Articulo implements java.io.Serializable {

	private Integer codigoArticulo;
	private String nombre;
	private int codigoGenero;
	private String plataforma;
	private Date fechaDeLanzamiento;
	private String informacionAdicional;
	private boolean disponibilidad;
	private int clave;

	public Articulo() {
	}

	public Articulo(String nombre, int codigoGenero, String plataforma, Date fechaDeLanzamiento, boolean disponibilidad,
			int clave) {
		this.nombre = nombre;
		this.codigoGenero = codigoGenero;
		this.plataforma = plataforma;
		this.fechaDeLanzamiento = fechaDeLanzamiento;
		this.disponibilidad = disponibilidad;
		this.clave = clave;
	}

	public Articulo(String nombre, int codigoGenero, String plataforma, Date fechaDeLanzamiento,
			String informacionAdicional, boolean disponibilidad, int clave) {
		this.nombre = nombre;
		this.codigoGenero = codigoGenero;
		this.plataforma = plataforma;
		this.fechaDeLanzamiento = fechaDeLanzamiento;
		this.informacionAdicional = informacionAdicional;
		this.disponibilidad = disponibilidad;
		this.clave = clave;
	}

	public Integer getCodigoArticulo() {
		return this.codigoArticulo;
	}

	public void setCodigoArticulo(Integer codigoArticulo) {
		this.codigoArticulo = codigoArticulo;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public int getCodigoGenero() {
		return this.codigoGenero;
	}

	public void setCodigoGenero(int codigoGenero) {
		this.codigoGenero = codigoGenero;
	}

	public String getPlataforma() {
		return this.plataforma;
	}

	public void setPlataforma(String plataforma) {
		this.plataforma = plataforma;
	}

	public Date getFechaDeLanzamiento() {
		return this.fechaDeLanzamiento;
	}

	public void setFechaDeLanzamiento(Date fechaDeLanzamiento) {
		this.fechaDeLanzamiento = fechaDeLanzamiento;
	}

	public String getInformacionAdicional() {
		return this.informacionAdicional;
	}

	public void setInformacionAdicional(String informacionAdicional) {
		this.informacionAdicional = informacionAdicional;
	}

	public boolean isDisponibilidad() {
		return this.disponibilidad;
	}

	public void setDisponibilidad(boolean disponibilidad) {
		this.disponibilidad = disponibilidad;
	}

	public int getClave() {
		return this.clave;
	}

	public void setClave(int clave) {
		this.clave = clave;
	}

}
