package modelo.hibernate;
// Generated 23-oct-2017 11:55:10 by Hibernate Tools 5.2.5.Final

import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;

/**
 * Compra generated by hbm2java
 */
public class Compra implements java.io.Serializable {
	@GeneratedValue(strategy=GenerationType.AUTO)
	private int codigoCompra;
	private String emailUsuario;
	private int codigoArticulo;

	public Compra() {
	}

	public Compra(int codigoCompra, String emailUsuario, int codigoArticulo) {
		this.codigoCompra = codigoCompra;
		this.emailUsuario = emailUsuario;
		this.codigoArticulo = codigoArticulo;
	}

	public int getCodigoCompra() {
		return this.codigoCompra;
	}

	public void setCodigoCompra(int codigoCompra) {
		this.codigoCompra = codigoCompra;
	}

	public String getEmailUsuario() {
		return this.emailUsuario;
	}

	public void setEmailUsuario(String emailUsuario) {
		this.emailUsuario = emailUsuario;
	}

	public int getCodigoArticulo() {
		return this.codigoArticulo;
	}

	public void setCodigoArticulo(int codigoArticulo) {
		this.codigoArticulo = codigoArticulo;
	}

}
