package modelo.hibernate;
// Generated 23-oct-2017 11:55:10 by Hibernate Tools 5.2.5.Final

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * DetalleCompra generated by hbm2java
 */
@Entity
@Table(name="detalle_compra")
public class DetalleCompra implements java.io.Serializable {
	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	private int idDetalle;
	
	private int emailUsuario;
	private int cantidad;
	private int precio;
	private int codigoCompra;
	private int codigoArticulo;
	private int claveArticulo;

	public DetalleCompra() {
	}

	public DetalleCompra(int emailUsuario, int cantidad, int precio, int codigoCompra) {
		this.emailUsuario = emailUsuario;
		this.cantidad = cantidad;
		this.precio = precio;
		this.codigoCompra = codigoCompra;
	}

	public Integer getIdDetalle() {
		return this.idDetalle;
	}

	public void setIdDetalle(Integer idDetalle) {
		this.idDetalle = idDetalle;
	}

	public int getEmailUsuario() {
		return this.emailUsuario;
	}

	public void setEmailUsuario(int emailUsuario) {
		this.emailUsuario = emailUsuario;
	}

	public int getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(int cantidad) {
		this.cantidad = cantidad;
	}

	public int getPrecio() {
		return this.precio;
	}

	public void setPrecio(int precio) {
		this.precio = precio;
	}

	public int getCodigoCompra() {
		return this.codigoCompra;
	}

	public void setCodigoCompra(int codigoCompra) {
		this.codigoCompra = codigoCompra;
	}

	public int getClaveArticulo() {
		return claveArticulo;
	}

	public void setClaveArticulo(int claveArticulo) {
		this.claveArticulo = claveArticulo;
	}

	public int getCodigoArticulo() {
		return codigoArticulo;
	}

	public void setCodigoArticulo(int codigoArticulo) {
		this.codigoArticulo = codigoArticulo;
	}

}
