package modelo.hibernate;
// Generated 23-oct-2017 11:55:10 by Hibernate Tools 5.2.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * DetalleCompra generated by hbm2java
 */
@Entity
@Table(name="detalle_compra")
public class DetalleCompra implements java.io.Serializable {
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name="id_detalle")
	private int idDetalle;
	@Column(name="codigo_articulo")
	private int codigoArticulo;
	@Column(name="nombre_articulo")
	private String nombreArticulo;
	@Column(name="cantidad")
	private int cantidad;
	@Column(name="precio")
	private float precio;
	@Column(name="clave_articulo")
	private String claveArticulo;
	@Column(name="codigo_compra")
	private int codigoCompra;
	
	
	public DetalleCompra( String nombreArticulo,int cantidad, float precio, int codigoArticulo, String claveArticulo,
			int codigoCompra) {
		super();
		this.nombreArticulo=nombreArticulo;
		this.cantidad = cantidad;
		this.precio = precio;
		this.codigoArticulo = codigoArticulo;
		this.claveArticulo = claveArticulo;
		this.codigoCompra = codigoCompra;
	}

	

	public DetalleCompra() {
	}



	public Integer getIdDetalle() {
		return this.idDetalle;
	}

	public void setIdDetalle(Integer idDetalle) {
		this.idDetalle = idDetalle;
	}



	public int getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(int cantidad) {
		this.cantidad = cantidad;
	}

	public float getPrecio() {
		return this.precio;
	}

	public void setPrecio(int precio) {
		this.precio = precio;
	}

	public int getCodigoCompra() {
		return this.codigoCompra;
	}

	public void setCodigoCompra(int codigoCompra) {
		this.codigoCompra = codigoCompra;
	}

	public String getClaveArticulo() {
		return claveArticulo;
	}

	public void setClaveArticulo(String claveArticulo) {
		this.claveArticulo = claveArticulo;
	}

	public int getCodigoArticulo() {
		return codigoArticulo;
	}

	public void setCodigoArticulo(int codigoArticulo) {
		this.codigoArticulo = codigoArticulo;
	}



	public void setIdDetalle(int idDetalle) {
		this.idDetalle = idDetalle;
	}



	public String getNombreArticulo() {
		return nombreArticulo;
	}



	public void setNombreArticulo(String nombreArticulo) {
		this.nombreArticulo = nombreArticulo;
	}

}
