package modelo.hibernate;
// Generated 23-oct-2017 11:55:10 by Hibernate Tools 5.2.5.Final

/**
 * DetalleCompra generated by hbm2java
 */
public class DetalleCompra implements java.io.Serializable {

	private Integer idDetalle;
	private int emailUsuario;
	private int cantidad;
	private int precio;
	private int codigoCompra;

	public DetalleCompra() {
	}

	public DetalleCompra(int emailUsuario, int cantidad, int precio, int codigoCompra) {
		this.emailUsuario = emailUsuario;
		this.cantidad = cantidad;
		this.precio = precio;
		this.codigoCompra = codigoCompra;
	}

	public Integer getIdDetalle() {
		return this.idDetalle;
	}

	public void setIdDetalle(Integer idDetalle) {
		this.idDetalle = idDetalle;
	}

	public int getEmailUsuario() {
		return this.emailUsuario;
	}

	public void setEmailUsuario(int emailUsuario) {
		this.emailUsuario = emailUsuario;
	}

	public int getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(int cantidad) {
		this.cantidad = cantidad;
	}

	public int getPrecio() {
		return this.precio;
	}

	public void setPrecio(int precio) {
		this.precio = precio;
	}

	public int getCodigoCompra() {
		return this.codigoCompra;
	}

	public void setCodigoCompra(int codigoCompra) {
		this.codigoCompra = codigoCompra;
	}

}
